"use client";

import React, { useState } from "react";
import { Zap, Copy, Check } from "lucide-react";

export default function JSONToGo() {
  const [input, setInput] = useState(`{\n  "user_id": 42,\n  "first_name": "Alex",\n  "is_admin": true,\n  "score": 99.5,\n  "tags": ["golang", "json"]\n}`);
  const [structName, setStructName] = useState("UserResponse");
  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const toPascalCase = (str: string) =>
    str
      .replace(/[^a-zA-Z0-9]/g, " ")
      .split(" ")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");

  const getGoType = (val: any): string => {
    if (typeof val === "number") return Number.isInteger(val) ? "int" : "float64";
    if (typeof val === "boolean") return "bool";
    if (Array.isArray(val)) return `[]${val.length > 0 ? getGoType(val[0]) : "interface{}"}`;
    if (typeof val === "object" && val !== null) return "struct";
    return "string";
  };

  const handleConvert = () => {
    try {
      setError(null);
      if (!input.trim()) return;
      const parsed = JSON.parse(input);
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
        throw new Error("Input must be a JSON object.");
      }

      const name = structName.trim() || "AutoGenerated";
      let code = `type ${name} struct {\n`;

      for (const key of Object.keys(parsed)) {
        const fieldName = toPascalCase(key);
        const goType = getGoType(parsed[key]);
        code += `\t${fieldName}\t${goType}\t\`json:"${key}"\`\n`;
      }

      code += `}\n`;
      setOutput(code);
    } catch (err: any) {
      setError(err.message || "Invalid JSON syntax");
      setOutput("");
    }
  };

  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2 mb-1">
        <Zap className="w-6 h-6 text-primary-theme" />
        JSON to Go Struct
      </h2>
      <p className="text-sm text-slate-500 mb-6">
        Generate Go (Golang) struct definitions with JSON tags instantly.
      </p>

      <div className="mb-4">
        <label className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-1 block">Struct Name</label>
        <input
          type="text"
          value={structName}
          onChange={(e) => setStructName(e.target.value)}
          className="w-full max-w-xs p-2.5 border border-slate-200 rounded-xl bg-slate-50 text-slate-800 font-mono text-sm focus:outline-none focus:border-primary-theme"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="flex flex-col">
          <label className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">JSON Input</label>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            className="flex-1 min-h-[250px] p-4 border border-slate-200 rounded-2xl bg-slate-50 text-slate-800 font-mono text-sm resize-none focus:outline-none focus:border-primary-theme"
          />
        </div>
        <div className="flex flex-col">
          <div className="flex justify-between items-center mb-2">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Go Struct Output</span>
            {output && (
              <button
                onClick={handleCopy}
                className="text-xs text-slate-600 hover:text-primary-theme flex items-center gap-1 font-semibold cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied" : "Copy Code"}
              </button>
            )}
          </div>
          <div className="flex-1 min-h-[250px] p-4 border border-slate-200 rounded-2xl bg-slate-50 text-slate-800 font-mono text-sm overflow-auto whitespace-pre">
            {error ? (
              <span className="text-red-500 font-semibold">{error}</span>
            ) : output ? (
              output
            ) : (
              <span className="text-slate-400 italic">Click Generate Go Struct...</span>
            )}
          </div>
        </div>
      </div>

      <div className="mt-6">
        <button
          onClick={handleConvert}
          disabled={!input.trim()}
          className="w-full bg-primary-theme hover:opacity-90 disabled:opacity-50 text-white font-semibold py-3 px-6 rounded-2xl transition shadow-sm flex items-center justify-center gap-2 cursor-pointer"
        >
          <Zap className="w-5 h-5" /> Generate Go Struct
        </button>
      </div>
    </div>
  );
}
